### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by monolieta** [digitallyserviced/semanticolor#30]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [semanticolor](https://github.com/xcezzz/semanticolor) package 3.6.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/mantum/.atom/packages/semanticolor/node_modules/sugar/array/internal/arrayAppend.js:15

RangeError: Maximum call stack size exceeded
    at Array.splice (<anonymous>)
    at arrayAppend (/packages/semanticolor/node_modules/sugar/array/internal/arrayAppend.js:15:14)
    at Function.append (/packages/semanticolor/node_modules/sugar/array/append.js:9:12)
    at Grammar.semanticolorGrammar.tokenizeLine (/packages/semanticolor/lib/semanticolor-grammar.js:76:18)
    at TextMateLanguageMode.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:412:50)
    at TextMateLanguageMode.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:407:23)
    at TextMateLanguageMode.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:295:47)
    at _.defer (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:279:63)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -3:08.8.0 intentions:highlight (input.hidden-input)
  4x -3:08.8.0 editor:move-to-end-of-word (input.hidden-input)
  2x -3:04.6.0 editor:select-to-end-of-word (input.hidden-input)
     -3:03.8.0 core:select-left (input.hidden-input)
     -3:03.4.0 core:paste (input.hidden-input)
     -3:02.9.0 core:save (input.hidden-input)
  2x -3:02.4.0 core:move-down (input.hidden-input)
  2x -3:01.6.0 core:move-up (input.hidden-input)
     -3:01.1.0 core:save (input.hidden-input)
     -2:36.7.0 atom-beautify:beautify-file (span.name.icon.jsx-icon.medium-blue)
     -2:31.7.0 core:undo (input.hidden-input)
     -2:31 core:save (input.hidden-input)
     -2:03.8.0 tree-view:show-in-file-manager (span.name.icon.jsx-icon.medium-blue)
  3x -1:46.6.0 tree-view:remove (div.tool-panel.tree-view)
     -1:21.3.0 core:save (input.hidden-input)
     -0:22.5.0 tree-view:remove (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
autocomplete-modules 2.0.0 
docblockr 0.13.7 
editorconfig 2.2.2 
file-icons 2.1.21 
fonts 3.0.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.85.0 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-gradle 0.0.5 
language-kotlin 0.5.0 
language-mongodb 0.3.1 
language-swift 0.5.0 
php-getters-setters 0.5.5 
pigments 0.40.2 
project-manager 3.3.6 
semanticolor 3.6.0 
sort-lines 0.18.0 
```

**Comment by sharedprophet** [comment]
If it’s not sensitive, could you include a sample file that causes this error? I had it happen today but that was because I opened a minified js file, so it was a large file all on one line. Was this something like that?
